# Generated by Django 2.2.13 on 2020-07-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_zona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camarazona',
            name='id_camara_zona',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
