# Generated by Django 2.2.13 on 2020-07-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0003_auto_20200701_0550'),
        ('camara_zona', '0002_auto_20200701_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='camarazona',
            name='id_instalacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instalacion.Instalacion'),
            preserve_default=False,
        ),
    ]
