# Generated by Django 2.2.13 on 2020-06-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20200629_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='mac_bluetooth',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='orientacion_display',
        ),
        migrations.AlterField(
            model_name='monitor',
            name='fondo_imagen',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='logotipo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
