# Generated by Django 2.2.13 on 2020-07-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0003_auto_20200701_0550'),
        ('monitor', '0003_auto_20200630_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='id_instalacion',
            field=models.ForeignKey(default=78888, on_delete=django.db.models.deletion.CASCADE, to='instalacion.Instalacion'),
            preserve_default=False,
        ),
    ]
