# Generated by Django 2.2.13 on 2020-06-25 03:51

import camara_zona.forms
import camara_zona.models
from django.db import migrations, models
import djongo.models.fields
import monitor.forms
import monitor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(default='', max_length=255)),
                ('direccion', models.CharField(default='', max_length=255)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('movil', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=255)),
                ('poblacion', models.CharField(default='', max_length=255)),
                ('provincia', models.CharField(default='', max_length=255)),
                ('codigo_postal', models.CharField(default='', max_length=10)),
                ('contacto_nombre', models.CharField(default='', max_length=255)),
                ('contacto_cargo', models.CharField(default='', max_length=255)),
                ('contacto_telefono', models.CharField(default='', max_length=20)),
                ('contacto_movil', models.CharField(default='', max_length=20)),
                ('contacto_email', models.CharField(default='', max_length=255)),
                ('tecnico_nombre', models.CharField(default='', max_length=255)),
                ('tecnico_cargo', models.CharField(default='', max_length=255)),
                ('tecnico_telefono', models.CharField(default='', max_length=20)),
                ('tecnico_movil', models.CharField(default='', max_length=20)),
                ('tecnico_email', models.CharField(default='', max_length=255)),
                ('instalacion_estado', models.BooleanField(default=True)),
                ('monitores', djongo.models.fields.ArrayField(blank=True, model_container=monitor.models.Monitor, model_form_class=monitor.forms.MonitorForm, null=True)),
                ('camara_zonas', djongo.models.fields.ArrayField(blank=True, model_container=camara_zona.models.CamaraZona, model_form_class=camara_zona.forms.CamaraZonaForm, null=True)),
            ],
        ),
    ]
