# Generated by Django 2.2.13 on 2020-07-01 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0002_instalacion_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
